---
title: The Muscle-BIDS Project
description: Standardizing the file format for Muscle MR processing
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji
- github-pages
- jekyll-remote-theme # add this line to the plugins list if you already have one

repository: muscle-bids/muscle-bids.github.io
